manifest:  
  remotes:  
    - name: zmkfirmware  
      url-base: https://github.com/zmkfirmware  
    - name: na-ka-no
      url-base: https://github.com/tadanaka  
  
  projects:  
    - name: zmk  
      remote: na-ka-no  # フォークしたリポジトリを参照  
      revision: main  # カスタムブランチ名  
      import: app/west.yml  
    - name: zmk-pmw3610-driver  
      remote: na-ka-no
      revision: main  
  
  self:  
    path: config
