manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tadanaka
      url-base: https://github.com/tadanaka
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cool642tb-mini
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: tadanaka
      revision: cool642tb-mini
  self:
    path: config
