manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tadanaka
      url-base: https://github.com/tadanaka
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: tadanaka
      revision: main
    - name: cool642tb-mini
      path: modules/my-battery
      revision: main
      url: https://github.com/tadanaka/cool642tb-mini
      
  self:
    path: config
